--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_info; Type: TABLE; Schema: public; Owner: malgum
--

CREATE TABLE public.ai_info (
    id bigint NOT NULL,
    ai_name character varying(255) NOT NULL,
    image_url character varying(255) NOT NULL
);


ALTER TABLE public.ai_info OWNER TO malgum;

--
-- Name: ai_info_id_seq; Type: SEQUENCE; Schema: public; Owner: malgum
--

ALTER TABLE public.ai_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ai_info; Type: TABLE DATA; Schema: public; Owner: malgum
--

COPY public.ai_info (id, ai_name, image_url) FROM stdin;
4       달님이  big_otter.png
3       햇님이  big_rabbit.png
2       Fuddy   big_fuddy.png
1       Tuddy   big_tuddy.png
\.


--
-- Name: ai_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: malgum
--

SELECT pg_catalog.setval('public.ai_info_id_seq', 4, true);


--
-- Name: ai_info ai_info_pkey; Type: CONSTRAINT; Schema: public; Owner: malgum
--

ALTER TABLE ONLY public.ai_info
    ADD CONSTRAINT ai_info_pkey PRIMARY KEY (id);


--
-- Name: ai_info uk2gn32fopquvts9is6jupdvs5g; Type: CONSTRAINT; Schema: public; Owner: malgum
--

ALTER TABLE ONLY public.ai_info
    ADD CONSTRAINT uk2gn32fopquvts9is6jupdvs5g UNIQUE (ai_name);


--
-- PostgreSQL database dump complete
--

